create table account_table (
        id bigint generated by default as identity,
        balance decimal(19,2)
        );
create table address_table (
        id bigint generated by default as identity,
        city varchar(255),
        person_id bigint
        );
create table person_table (
        id bigint generated by default as identity,
        account_id bigint
        );